Split APIHelper out into its own file
JOJ0/synadm pull request #137
Opened 2023-11-20 20:47 UTC by n-peugnet

This allow to only import it when needed, speeding up the CLI for easy tasks, especially the [auto-completion provided by click][1] (that I intend to add to the Debian package). This is most noticable when site packages are enabled (as with the command `python -m virtualenv --system-site-packages`) or on global installations, like with the official Debian package.

Before

	$time synadm > /dev/null
	real	0m0,610s
	user	0m0,537s
	sys	0m0,072s

After

	$time synadm > /dev/null
	real	0m0,086s
	user	0m0,077s
	sys	0m0,009s

[1]: https://click.palletsprojects.com/en/latest/shell-completion/

2023-11-20 21:20 UTC, n-peugnet commented
> Some actual benchmarking

Thank you, I wasn't motivated enough to do it!

> This really looks like filesystem caching in action, so this benchmark likely isn't good.

Not really, I didn't take the first run, subsequent runs are all about the same time.

Also note that it really depends on the quantity of python libraries installed on the system. For instance in a bare-bones virtualenv it is almost not noticeable.

2023-11-20 21:24 UTC, n-peugnet commented
> > Also note that it really depends on the quantity of python libraries installed on the system. For instance in a bare-bones virtualenv it is almost not noticeable.
> 
> Hmm, I'll try barebones venv in both cases later.

Sorry I meant the difference is almost not noticeable. Meaning it is almost the same time for both my changes and master.

2023-11-20 22:01 UTC, n-peugnet commented
Some more numbers to explain the differences:

```console
$ # master in venv made with `python -m virtualenv --system-site-packages`
$ strace synadm 2>&1 | wc -l
13251
$ # this branche in venv made with `python -m virtualenv --system-site-packages`
$ strace synadm 2>&1 | wc -l
1668
$ # master in normal venv
$ strace synadm 2>&1 | wc -l
4448
$ # this branch in normal venv
$ strace synadm 2>&1 | wc -l
1537
```

2023-11-23 09:22 UTC, JOJ0 requested changes
Hi to both of you,
awesome idea. Splitting out into a separate file is a good idea even if it was not for performance. I didn't realize that there is a Debian package and you are the maintainer @n-peugnet, that is great news as well! Thanks so much for taking care of that. Tab completion for synadm also sounds like a very handy feature for the package. We certainly should work towards making that a pleasent user experience.

One change request: Please let's name that file `_helper.py`.

2023-11-23 11:15 UTC, n-peugnet commented
> I didn't realize that there is a Debian package and you are the maintainer @n-peugnet

I am not the [official maintainer](https://tracker.debian.org/pkg/synadm) but I intend to send him a patch to add the completion script in the package.

> Tab completion for synadm also sounds like a very handy feature for the package. We certainly should work towards making that a pleasent user experience.

This is exactly when testing this completion script (generated by click) that loads the python project each time that I noticed the startup was quite slow.

> One change request: Please let's name that file `_helper.py`.

I can do that in a few days. Not that much time right now.

2023-11-23 13:50 UTC, n-peugnet commented
> would it be fine if i did it?

Yes of course!

2023-11-29 10:13 UTC, JOJ0 commented
Hi, sorry for the delay. I just wanted to quickly add some refinements to the docstrings of the modules. Are you sure you have maintainer edits enabled?

2023-11-29 10:14 UTC, JOJ0 commented on synadm/cli/__init__.py
>  """ CLI base functions and settings
```suggestion
""" Contains CLI root-level commands; Subcommands are imported at the bottom of
+this file
```

2023-11-29 13:37 UTC, n-peugnet commented on synadm/cli/__init__.py
>  """
> Are you sure you have maintainer edits enabled?

I'm really sorry I didn't find how to check or change this. But I thought it was on by default.

About this suggestion, I think you meant this:

```suggestion
""" CLI root-level commands; Subcommands are imported at the bottom of file
"""
```

2023-11-29 14:31 UTC, JOJ0 commented on synadm/cli/__init__.py
>  """
No problem at all :-)

2023-11-29 15:55 UTC, merged