Shadow-ban command
JOJ0/synadm pull request #57
Opened 2022-02-24 21:47 UTC by Ascurius

Hi JOJ0,

I quickly implemented a first appraoch to the shadow-ban command, based on your work. Hopefully this is useful to you.

If have tried to follow your documentation and command style. However, please let me know if my implementation approach does meet your requirements regarding documentation or command structure.

Additionally I added the `env` folder for virtual python environments to the `.gitignore`

2022-02-24 22:34 UTC, JOJ0 commented
Awesome! Please add the command to the checkbox list in readme.md.

You could also add a little more description to what it does exactly to the commands docstring which will then land up in --help. First line is what the user sees on main command -h, the rest is shown in subcommand -h

I usually steel bits and pieces from the synapse admin api docs, try to shorten. The goal is to be clear about what will happen but but not in all fancy detail like the synapse admin api docs.

2022-02-25 11:59 UTC, Ascurius commented
I have added more description to the command (8a29b9b9923fe7fbb25af93fe2fab45a90a3a47e) and also added it to the command checkbox list in the README.md (3d27354530566a9d72086dcc26ea0151fc970432)

2022-02-28 19:25 UTC, JOJ0 requested changes
Sorry for the delay. :-) A view cosmetical changes, besides that LGTM and ready to merge :-)

2022-02-28 19:25 UTC, JOJ0 commented on synadm/api.py
> +            user_id (string): The user to be baned/unbanned
Typo: banned

2022-02-28 19:25 UTC, JOJ0 commented on synadm/api.py
> +            unban (boolean): Unban the specified user
End "sentences" with dot.

2022-02-28 19:25 UTC, JOJ0 commented on synadm/cli/user.py
> +    helper.output(user_ban)
This API seems to always return empty dict {} when no error occured. If you want but not strictly required you could prettify that for human mode. Something like this: https://github.com/Ascurius/synadm/blob/master/synadm/cli/user.py#L127-L134

2022-02-28 19:25 UTC, JOJ0 commented on synadm/cli/user.py
> +    may lead to confusing or broken behaviour for the client.
Please keep the lines 79 characters max. Don't know what editor you are using but with something `vim`'ish the quickest way would be marking the lines and pressing `gq`

2022-02-28 19:25 UTC, JOJ0 commented on synadm/cli/user.py
> +    Generally, it is more appropriate to ban or kick abusive users.
There is some redundant spaces.

2022-02-28 19:25 UTC, JOJ0 commented on synadm/cli/user.py
> +    may lead to confusing or broken behaviour for the client.
Also there is a redundant space after client.

2022-03-02 22:03 UTC, Ascurius commented
Sorry for my late response. I modified the section you mentioned according to your requirements. Besides, I have added some additional body to the shadow-ban command for the human mode. Please let me know if anything else needs to be changed.

2022-03-04 08:45 UTC, merged

2022-03-04 08:47 UTC, JOJ0 commented
No worries, all good, thanks a lot for the changes. Merged and happy synadm got a nice new feature. Many thanks!

2022-03-04 08:48 UTC, JOJ0 commented
BTW I'd like to contact you because of something else and invite you to synadm:peek-a-boo.at